org.gradle.jvmargs=-Xmx3g

mod_version=0.7.0
maven_group=net.ccbluex
archives_base_name=librebounce

# Kotlin
# https://kotlinlang.org/releases.html
# DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING!
kotlin_version=2.0.21
kotlin_coroutines_version=1.10.1

forgegradle_version = FG_2.1-a3d86a59c0-1
mixingradle_version = ae2a80e
