pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://maven.minecraftforge.net/" }
        maven { 
            url = 'https://jitpack.io'
            content {
                includeGroupByRegex 'com\\.github\\..*'
            }
        }
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case "net.minecraftforge.gradle.forge":
                    useModule("com.github.ccbluex:ForgeGradle:a3d86a59c0")
                    break
                case "org.spongepowered.mixin":
                    useModule("com.github.xcfrg:mixingradle:ae2a80e")
                    break
            }
        }
    }
    plugins {
        id "org.jetbrains.kotlin.jvm" version kotlin_version
    }
}

rootProject.name = 'LiquidBounce'
